<div class="row">
    <div class="span12">
        <h2>Crawler</h2>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('crawler',
                array(
                    'action' => 'index',
                )
            )
        );
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();

        echo $this->form()->openTag($form);

        echo $this->formHelper($form)->formInput($form->get('url'));

        echo '<div class="control-group">';
        echo '<div class="controls">';
        echo $this->formSubmit($form->get('submit'));
        echo '</div>';
        echo '</div>';

        echo $this->form()->closeTag();
        ?>
    </div>
</div>

<div class="row">
    <div class="span12">
        <ul>
        <?php
        print_r('<pre>' . $this->crawlerEntity . '</pre>');
//        foreach($this->crawlerEntity->getCrawledUrls() as $url=>$total) {
//            echo '<li>' . $url . ' (' . $total . ')</li>';
//        }
        ?>
        </ul>
    </div>
</div>