<div class="row">
    <div class="span12">
        <h2>Crawler</h2>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('url',
                array(
                    'action' => 'crawl',
                )
            )
        );
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();

        echo $this->form()->openTag($form);

        echo $this->formHelper($form)->formInput($form->get('protocol'));
        echo $this->formHelper($form)->formInput($form->get('hostname'));
        echo $this->formHelper($form)->formInput($form->get('port'));
        echo $this->formHelper($form)->formInput($form->get('depth'));
        echo $this->formHelper($form)->formInput($form->get('limit'));

        echo '<div class="control-group">';
        echo '<div class="controls">';
        echo $this->formSubmit($form->get('submit'));
        echo '</div>';
        echo '</div>';

        echo $this->form()->closeTag();
        ?>
    </div>
</div>