<div class="row">
    <div class="span12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Url</th>
                <th>Depth</th>
                <th>Limit</th>
                <th>Duration (s)</th>
                <th>Queued Urls</th>
                <th>Skipped Urls</th>
                <th>Failed Urls</th>
                <th>Created On</th>
                <th>Updated On</th>
            </tr>
            </thead>
            <tbody>
        <?php
        foreach($this->urlList as $url) {
            echo '<tr>';
            echo '<td><a href="' . $this->url('crawled-url', array('id' => $url->getId())) . '">' . $url->getUrl() . '<a/></td>';
            echo '<td>' . $url->getDepth() . '</td>';
            echo '<td>' . $url->getLimit() . '</td>';
            echo '<td>' . $url->getDuration() . '</td>';
            echo '<td>' . $url->getQueued() . '</td>';
            echo '<td>' . $url->getSkipped() . '</td>';
            echo '<td>' . $url->getFailed() . '</td>';
            echo '<td>' . $this->date($url->getCreatedOn()) . '</td>';
            echo '<td>' . $this->date($url->getUpdatedOn()) . '</td>';
            echo '</tr>';
        }
        ?>
            </tbody>
        </table>
    </div>
</div>